### ISSUE TITLE
jcenter entry is bad, and mavenCentral is non-existent

### ISSUE THREAD

**Issue by inder123** [steveliles/Foredroid#16]
I tried to use the gradle dependency as: 
compile 'com.sjl:Foredroid:1.0.1'
This package doesn't exist in jcenter or maven-central. 
Per this page: 
https://bintray.com/steveliles/maven/Foredroid/1.0.1?versionPath=%2Fsteveliles%2Fmaven%2FForedroid%2F1.0.1

The package that is available is: compile 'Foredroid:Foredroid:unspecified'

Can you publish 1.0.2 version that fixes these problems? Thanks.

**Comment by ryan-hodgman** [comment]
Verified, there was something wrong with the upload to these distributors. Would appreciate a fix if you have some time @steveliles? (https://dev.redbridge.se/artifactory/list/jcenter/com/sjl/Foredroid/)

**Comment by steveliles** [comment]
@inder123 @ryan-hodgman sorry guys, I had a go at this a few weeks ago and got nowhere and haven't been able to find time since. 

The problem is somewhere in the gradle jcenter config. Something changed in the jcenter API in the time since the first release, so the original config no longer worked. I spent an hour trying various updates but got nowhere  and had to give it up. If anyone is up-to-date with gradle/jcenter and could take a look I'd appreciate any help ...

**Comment by steveliles** [comment]
@inder123 @ryan-hodgman so I gave it another shot now and i think 1.0.2 has published successfully ...

**Comment by inder123** [comment]
Yes, this worked! Thank you.

**Comment by ryan-hodgman** [comment]
Great, thanks!
