### ISSUE TITLE
Closing Interstitial became background instead foreground

### ISSUE THREAD

**Issue by BoschAlejandro** [steveliles/Foredroid#4]
When closing an interstital ad from admob the Foreground instance became background instead foreground.

It resolves changing the call onActivityResumed to:
    @Override
    public void onActivityResumed(Activity activity) {
        current = activity;
    }

Best regards and good job!
Alex.

**Comment by steveliles** [comment]
Thanks for the bug report :) 

There's some unfortunate non-determinism in the current implementation that possibly triggers this problem. An interesting pull-request #3 also arrived today that may resolve your problem, since it completely removes the non-determinism. I don't yet know if it introduces other issues as I haven't had a chance to try it out.
